# Generated by Django 5.2.8 on 2025-12-08 00:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('jobs', '0001_initial'),
        ('networks', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChangeJobs',
            new_name='ChangeJob',
        ),
    ]
