# Generated by Django 5.2.8 on 2025-12-07 03:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('lan_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('wan_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=32)),
                ('device_type', models.CharField(max_length=100)),
                ('firmware_version', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
