# Generated by Django 5.2.8 on 2025-12-07 03:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerakiNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('meraki_orgnization_id', models.CharField(max_length=50)),
                ('network_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('time_zone', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('product_types', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orgnization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='organizations.organization')),
            ],
        ),
    ]
