# Generated by Django 5.2.8 on 2025-12-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merakinetwork',
            old_name='meraki_orgnization_id',
            new_name='meraki_organization_id',
        ),
        migrations.RenameField(
            model_name='merakinetwork',
            old_name='orgnization',
            new_name='organization',
        ),
    ]
