# Generated by Django 5.2.8 on 2025-12-13 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sync_target', models.CharField(choices=[('organization', 'Organization'), ('networks', 'Networks'), ('devices', 'Devices'), ('policies', 'Policies'), ('full', 'Full Sync')], default='full', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('networks_fetched', models.IntegerField(default=0)),
                ('devices_fetched', models.IntegerField(default=0)),
                ('error_messages', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='organizations.organization')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_syncs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
