# Generated by Django 5.2.8 on 2025-12-09 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_rename_changejobs_changejob'),
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRuleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.JSONField()),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_applied_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firewall_updates', to='jobs.changejob')),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_ruleset', to='networks.merakinetwork')),
            ],
        ),
        migrations.CreateModel(
            name='SSIDConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.JSONField()),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_applied_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssid_updates', to='jobs.changejob')),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssid_configurations', to='networks.merakinetwork')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ports', models.JSONField()),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_applied_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch_updates', to='jobs.changejob')),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='switch_configuration', to='networks.merakinetwork')),
            ],
        ),
    ]
